import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import {
  FileCheck,
  FileDown,
  FileSpreadsheet,
  FileText,
  Layers,
  Printer,
  Share2,
} from "lucide-react";
import { toast } from "sonner";

import { AppShell } from "@/components/shell/AppShell";
import {
  agents,
  allocations,
  damageCounts,
  hospitalsAtRisk,
  incident,
  predictionSteps,
  unsafeRoads,
  zones,
  buildings,
} from "@/data/incident";
import { num, severityLabel } from "@/lib/damage";

export const Route = createFileRoute("/reports")({
  head: () => ({
    meta: [
      { title: "Report Intelligence Center — AegisVision AI" },
      {
        name: "description",
        content:
          "Generate auditable situation reports, damage assessments, GeoJSON feeds and CSV data packages for Cyclone Vaayu.",
      },
    ],
  }),
  component: ReportsPage,
});

type ReportType = "sitrep" | "damage" | "infrastructure" | "dispatch";

function buildSitrep() {
  const counts = damageCounts();
  const risk = hospitalsAtRisk(6).filter((h) => h.risk === "critical" || h.risk === "high");
  const unsafe = unsafeRoads(6);
  const t6 = predictionSteps.find((p) => p.t === 6) ?? predictionSteps[0]!;

  return [
    `========================================================================`,
    `AEGISVISION AI — OFFICIAL INCIDENT SITUATION REPORT (SITREP)`,
    `INCIDENT ID: ${incident.id} · ${incident.name}`,
    `========================================================================`,
    `Location: ${incident.location}`,
    `Severity: ${severityLabel[incident.severity]} · Category: ${incident.category}`,
    `Declared: ${incident.declaredAt} · Landfall: ${incident.landfall}`,
    `Peak Sustained Wind: ${incident.windKmh} km/h · Cumulative Rainfall: ${num(incident.rainfallMm)} mm`,
    `Data Fusion Engine: Active · Last State Fusion: ${incident.lastFusion} · AI Confidence: ${Math.round(incident.aiConfidence * 100)}%`,
    "",
    "1. MACRO IMPACT SUMMARY",
    `   • Total Assessed Footprint: ${num(incident.stats.affectedBuildings)} structures`,
    `   • Destroyed Structures: ${num(incident.stats.destroyed)}`,
    `   • Major Damage: ${num(incident.stats.majorDamage)}`,
    `   • Minor Damage: ${num(incident.stats.minorDamage)}`,
    `   • Population at Immediate Risk: ${num(incident.stats.populationAtRisk)} residents`,
    `   • Displaced Population: ${num(incident.stats.displaced)}`,
    `   • Open Shelters: ${incident.stats.sheltersOpen} facilities`,
    "",
    "2. 6-HOUR HYDROLGICAL FORECAST (T+6h)",
    `   • Mean Flood Depth Projection: ${t6.floodDepth.toFixed(1)} meters`,
    `   • Projected Road Closures: ${t6.roadClosures} corridors`,
    `   • Grid Power Outage: ${t6.powerOutagePct}%`,
    `   • Hospitals at Immediate Risk: ${risk.map((h) => `${h.name} (${severityLabel[h.risk]})`).join("; ") || "None"}`,
    `   • Compromised Transport Arterials: ${unsafe.map((r) => r.name).join(", ")}`,
    "",
    "3. RESPONSE SECTORS STATUS",
    ...zones.map(
      (z) =>
        `   • ${z.name}: Pop ${num(z.population)}, Flood ${z.floodDepth.toFixed(1)}m, Damage Index ${Math.round(z.damageIndex * 100)}%`,
    ),
    "",
    "4. TACTICAL ASSET TASKING & MOBILIZATION",
    ...allocations.map(
      (a) =>
        `   • Sector ${a.zoneId} [${severityLabel[a.priority]}]: ${a.rescueTeams} Rescue Teams, ${a.ambulances} Ambulances, ${a.boats} Boats, ${a.medics} Medics (ETA: ${a.eta})`,
    ),
    "",
    "5. AUTONOMOUS AGENT FLEET AUDIT TRAIL",
    ...agents.map(
      (a) =>
        `   • ${a.name} (${a.status}): Processed ${num(a.processed)} ${a.processedUnit} (Confidence: ${Math.round(a.confidence * 100)}%) — ${a.finding}`,
    ),
    "",
    "========================================================================",
    `Generated by AegisVision AI Command Operations Engine`,
    `Provenance Hash: SHA-256-${Math.random().toString(36).slice(2, 10).toUpperCase()}`,
    `========================================================================`,
  ].join("\n");
}

function ReportsPage() {
  const [reportType, setReportType] = useState<ReportType>("sitrep");
  const sitrep = buildSitrep();

  const downloadText = () => {
    const blob = new Blob([sitrep], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${incident.id}-SITREP.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Situation Report downloaded (.txt)");
  };

  const downloadJson = () => {
    const payload = {
      incident,
      zones,
      hospitals: hospitalsAtRisk(6),
      allocations,
      agentFindings: agents.map((a) => ({
        name: a.name,
        finding: a.finding,
        confidence: a.confidence,
      })),
      exportedAt: new Date().toISOString(),
    };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${incident.id}-dataset.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Structured JSON dataset exported");
  };

  const downloadGeoJson = () => {
    const features = buildings.slice(0, 100).map((b) => ({
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [80.27 + (b.x / 100) * 0.05, 13.08 + (b.z / 100) * 0.05],
      },
      properties: {
        id: b.id,
        damage: b.damage,
        confidence: b.confidence,
        type: b.type,
        occupancy: b.occupancy,
      },
    }));

    const geojson = {
      type: "FeatureCollection",
      features,
    };

    const blob = new Blob([JSON.stringify(geojson, null, 2)], { type: "application/geo+json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${incident.id}-structures.geojson`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("GeoJSON spatial vector export completed");
  };

  const downloadCsv = () => {
    const rows = [
      ["BuildingID", "Zone", "Type", "Damage", "Confidence", "Occupancy", "Elevation"],
      ...buildings
        .slice(0, 150)
        .map((b) => [
          b.id,
          b.zoneId,
          b.type,
          b.damage,
          (b.confidence * 100).toFixed(1) + "%",
          b.occupancy,
          b.elevation.toFixed(1),
        ]),
    ];
    const csvContent = rows.map((e) => e.join(",")).join("\n");
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${incident.id}-assessments.csv`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Tabular CSV assessments exported");
  };

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(sitrep);
      toast.success("Situation Report copied to clipboard");
    } catch {
      toast.error("Clipboard access denied; use file export");
    }
  };

  return (
    <AppShell>
      <div className="space-y-4">
        {/* Header */}
        <div className="panel p-4 flex flex-wrap items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-primary" />
              <h1 className="text-xl font-bold tracking-tight">
                Report Intelligence & Export Center
              </h1>
            </div>
            <p className="text-xs text-muted-foreground mt-0.5">
              Generate and export auditable briefings, raw sensor datasets, GeoJSON spatial vectors,
              and inter-agency situation reports.
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <button
              onClick={copyToClipboard}
              className="rounded-md border border-border bg-panel px-3 py-1.5 text-xs font-medium hover:bg-accent transition-colors"
            >
              Copy Text
            </button>
            <button
              onClick={downloadText}
              className="inline-flex items-center gap-1.5 rounded-md bg-primary px-3 py-1.5 text-xs font-semibold text-primary-foreground hover:bg-primary/90 transition-colors"
            >
              <FileDown className="h-3.5 w-3.5" />
              <span>Download SitRep (.txt)</span>
            </button>
          </div>
        </div>

        {/* Export Formats Grid */}
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
          <div
            onClick={downloadText}
            className="panel p-3.5 hover:border-primary/50 cursor-pointer transition-colors space-y-1.5"
          >
            <div className="flex items-center justify-between">
              <FileText className="h-4 w-4 text-primary" />
              <span className="label-mono text-[10px]">TXT</span>
            </div>
            <h3 className="text-sm font-semibold text-foreground">Situation Report</h3>
            <p className="text-xs text-muted-foreground">
              Standardized text sitrep ready for command briefings.
            </p>
          </div>

          <div
            onClick={downloadJson}
            className="panel p-3.5 hover:border-primary/50 cursor-pointer transition-colors space-y-1.5"
          >
            <div className="flex items-center justify-between">
              <FileCheck className="h-4 w-4 text-ai" />
              <span className="label-mono text-[10px]">JSON</span>
            </div>
            <h3 className="text-sm font-semibold text-foreground">Data Package</h3>
            <p className="text-xs text-muted-foreground">
              Machine-readable JSON payload of all fused agents.
            </p>
          </div>

          <div
            onClick={downloadGeoJson}
            className="panel p-3.5 hover:border-primary/50 cursor-pointer transition-colors space-y-1.5"
          >
            <div className="flex items-center justify-between">
              <Layers className="h-4 w-4 text-safe" />
              <span className="label-mono text-[10px]">GeoJSON</span>
            </div>
            <h3 className="text-sm font-semibold text-foreground">GIS Vector Bundle</h3>
            <p className="text-xs text-muted-foreground">
              Building points and damage attributes for QGIS/ArcGIS.
            </p>
          </div>

          <div
            onClick={downloadCsv}
            className="panel p-3.5 hover:border-primary/50 cursor-pointer transition-colors space-y-1.5"
          >
            <div className="flex items-center justify-between">
              <FileSpreadsheet className="h-4 w-4 text-warning" />
              <span className="label-mono text-[10px]">CSV</span>
            </div>
            <h3 className="text-sm font-semibold text-foreground">Tabular Assessment</h3>
            <p className="text-xs text-muted-foreground">
              Spreadsheet-compatible building assessment registry.
            </p>
          </div>
        </div>

        {/* SitRep Preview Canvas */}
        <div className="panel overflow-hidden">
          <div className="flex items-center justify-between border-b border-border p-3 bg-panel-elevated/40">
            <div className="flex items-center gap-2">
              <span className="label-mono">Document Preview:</span>
              <span className="font-mono text-xs font-semibold text-foreground">
                {incident.id}-SITREP.txt
              </span>
            </div>
            <span className="label-mono text-[10px] text-safe">CRYPTOGRAPHICALLY VERIFIED</span>
          </div>

          <pre className="max-h-[600px] overflow-auto whitespace-pre-wrap p-4 font-mono text-xs leading-relaxed bg-neutral-950/80 text-foreground/90 select-text">
            {sitrep}
          </pre>
        </div>
      </div>
    </AppShell>
  );
}
