/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BuildingsRouteImport } from './routes/buildings'
import { Route as DronesRouteImport } from './routes/drones'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as MapRouteImport } from './routes/map'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResponseRouteImport } from './routes/response'
import { Route as RoutingRouteImport } from './routes/routing'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TwinRouteImport } from './routes/twin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsRoute = BuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const DronesRoute = DronesRouteImport.update({
  id: '/drones',
  path: '/drones',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponseRoute = ResponseRouteImport.update({
  id: '/response',
  path: '/response',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutingRoute = RoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/buildings': typeof BuildingsRoute
  '/drones': typeof DronesRoute
  '/evidence': typeof EvidenceRoute
  '/explainability': typeof ExplainabilityRoute
  '/graph': typeof GraphRoute
  '/incidents': typeof IncidentsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/map': typeof MapRoute
  '/predictions': typeof PredictionsRoute
  '/reports': typeof ReportsRoute
  '/response': typeof ResponseRoute
  '/routing': typeof RoutingRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/twin': typeof TwinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/buildings': typeof BuildingsRoute
  '/drones': typeof DronesRoute
  '/evidence': typeof EvidenceRoute
  '/explainability': typeof ExplainabilityRoute
  '/graph': typeof GraphRoute
  '/incidents': typeof IncidentsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/map': typeof MapRoute
  '/predictions': typeof PredictionsRoute
  '/reports': typeof ReportsRoute
  '/response': typeof ResponseRoute
  '/routing': typeof RoutingRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/twin': typeof TwinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/buildings': typeof BuildingsRoute
  '/drones': typeof DronesRoute
  '/evidence': typeof EvidenceRoute
  '/explainability': typeof ExplainabilityRoute
  '/graph': typeof GraphRoute
  '/incidents': typeof IncidentsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/map': typeof MapRoute
  '/predictions': typeof PredictionsRoute
  '/reports': typeof ReportsRoute
  '/response': typeof ResponseRoute
  '/routing': typeof RoutingRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/twin': typeof TwinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/alerts'
    | '/analytics'
    | '/buildings'
    | '/drones'
    | '/evidence'
    | '/explainability'
    | '/graph'
    | '/incidents'
    | '/infrastructure'
    | '/map'
    | '/predictions'
    | '/reports'
    | '/response'
    | '/routing'
    | '/scenarios'
    | '/settings'
    | '/twin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/alerts'
    | '/analytics'
    | '/buildings'
    | '/drones'
    | '/evidence'
    | '/explainability'
    | '/graph'
    | '/incidents'
    | '/infrastructure'
    | '/map'
    | '/predictions'
    | '/reports'
    | '/response'
    | '/routing'
    | '/scenarios'
    | '/settings'
    | '/twin'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/alerts'
    | '/analytics'
    | '/buildings'
    | '/drones'
    | '/evidence'
    | '/explainability'
    | '/graph'
    | '/incidents'
    | '/infrastructure'
    | '/map'
    | '/predictions'
    | '/reports'
    | '/response'
    | '/routing'
    | '/scenarios'
    | '/settings'
    | '/twin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BuildingsRoute: typeof BuildingsRoute
  DronesRoute: typeof DronesRoute
  EvidenceRoute: typeof EvidenceRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  GraphRoute: typeof GraphRoute
  IncidentsRoute: typeof IncidentsRoute
  InfrastructureRoute: typeof InfrastructureRoute
  MapRoute: typeof MapRoute
  PredictionsRoute: typeof PredictionsRoute
  ReportsRoute: typeof ReportsRoute
  ResponseRoute: typeof ResponseRoute
  RoutingRoute: typeof RoutingRoute
  ScenariosRoute: typeof ScenariosRoute
  SettingsRoute: typeof SettingsRoute
  TwinRoute: typeof TwinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings': {
      id: '/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof BuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drones': {
      id: '/drones'
      path: '/drones'
      fullPath: '/drones'
      preLoaderRoute: typeof DronesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/response': {
      id: '/response'
      path: '/response'
      fullPath: '/response'
      preLoaderRoute: typeof ResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routing': {
      id: '/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof RoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  BuildingsRoute: BuildingsRoute,
  DronesRoute: DronesRoute,
  EvidenceRoute: EvidenceRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  GraphRoute: GraphRoute,
  IncidentsRoute: IncidentsRoute,
  InfrastructureRoute: InfrastructureRoute,
  MapRoute: MapRoute,
  PredictionsRoute: PredictionsRoute,
  ReportsRoute: ReportsRoute,
  ResponseRoute: ResponseRoute,
  RoutingRoute: RoutingRoute,
  ScenariosRoute: ScenariosRoute,
  SettingsRoute: SettingsRoute,
  TwinRoute: TwinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
